site_name: Transposon Annotations and Mapping

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    features:
        - navigation.expand
        - navigation.indexes
        - navigation.sections
        - navigation.tabs

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - wikilinks
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      clickable_checkbox: true

plugins:
  - search
  - roamlinks
  - mermaid2:
        arguments:
          securityLevel: 'loose'


      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
    - Home: index.md
    - Transposon Annotations: 
      - Overall Workflow: transposon_anno_workflow/a0_overall_anno_workflow.md
      - Step 1 - TEUlt setup: transposon_anno_workflow/a1_TEUlt_setup.md
      - Step 2.1 - TEUlt annotations: transposon_anno_workflow/a2_1_anno_TEUlt.md
      - Step 2.2 - Manual annotations: 
        - Manual annotations: transposon_anno_workflow/a2_2_anno_manual.md
        - MUST: transposon_anno_workflow/prgrm_MUST.md
        - SINE Finder: transposon_anno_workflow/prgrm_SINEFind.md
        - LTR Harvest: transposon_anno_workflow/prgrm_LTRHarvest.md
        - LTR Finder: transposon_anno_workflow/prgrm_LTRFinder.md
        - LTR Retriever: transposon_anno_workflow/prgrm_LTRRet.md
      - Step 3 - Combine annotations: transposon_anno_workflow/a3_anno_combine.md
      - Step 4 - Parse annotations: transposon_anno_workflow/a4_anno_parse.md
      - Step 5 - Run TEUlt pipeline: transposon_anno_workflow/a5_anno_pipeline.md
      - Step 6 - Annotation stats (NOT size filtered): transposon_anno_workflow/a6_anno_stats.md
      - Step 7 - Size filtering: transposon_anno_workflow/a7_size_filter.md
      - Step 8 - Analysis and graphs: transposon_anno_workflow/a8_make_pictures.md
    - Transposon Mapping:
      - Overall Workflow: transposon_mapping_workflow/m0_overall_mapping_workflow.md
      - Step 1 - Determine overlap: transposon_mapping_workflow/m1_bedtools_intersect.md
      - Step 2 - Jupyter notebook party: transposon_mapping_workflow/m2_jupyterparty.md
      - Step 3 - Find TEs that actually moved: transposon_mapping_workflow/m3_findactuallymoved.md
      - Step 4 - RIdeogram: transposon_mapping_workflow/m4_rideogram.md
    - Code:
      - scripts/index.md
      

