site_name: Transposon Annotations and Mapping

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    features:
        - navigation.expand
        - navigation.indexes
        - navigation.sections

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

  - wikilinks
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      clickable_checkbox: true

plugins:
  - search
  - roamlinks
  - mermaid2:
        arguments:
          securityLevel: 'loose'


      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js


nav:
  - Transposon Annotations:
    - transposon_anno_workflow/index.md
    - Page 1: transposon_anno_workflow/a0_overall_anno_workflow.md
    - Page 2: transposon_anno_workflow/a1_TEUlt_setup.md
    - Page 3: transposon_anno_workflow/a2_1_anno_TEUlt.md